#!/bin/bash
export TWITTER_API_KEY=""
export TWITTER_API_SECRET=""
export TWITTER_ACCESS_TOKEN=""
export TWITTER_ACCESS_TOKEN_SECRET=""
/opt/build-ceres; java -jar /opt/ceres/target/ceres-standalone.jar
